import { buildChapter, buildSection, s, x, sectionWithDiagram } from "../concepts-bl-helpers";

export const chapter07BlQuickWinsVsLongTerm = buildChapter({
  slug: "bl-quick-wins-vs-long-term",
  number: 7,
  shortTitle: "Quick Wins vs Long-Term AI",
  title: "Quick Wins vs Long-Term AI — Managing the Horizon Tension",
  readingMinutes: 20,
  summary:
    "Every AI programme must balance near-term wins that build confidence and deliver ROI against long-term bets that create structural competitive advantage. Getting this balance wrong — too much quick win, too much long-term, or the wrong sequencing — is one of the most common reasons AI programmes underdeliver. This chapter gives business leaders the framework and the discipline to manage both horizons intentionally.",
  keyTakeaway:
    "Quick wins are not the opposite of long-term thinking — they are the evidence base and capability foundation that long-term bets require. The business leader's job is to sequence them deliberately, protect each horizon from the other's pressure, and communicate the portfolio balance in a way that earns sustained stakeholder support.",
  pmCallout:
    "As a business leader: both horizons need you as an active sponsor. Quick wins will be deprioritised by technology teams in favour of interesting long-term problems. Long-term bets will be defunded by finance in favour of visible near-term returns. You are the counterpressure in both directions.",
  sections: [
    sectionWithDiagram({
      number: "7.1",
      title: "Why Quick Wins Matter",
      subtitle: "The evidence cadence that keeps the programme alive",
      take: "Quick wins matter because they are the only evidence that an AI programme is producing value before long-term bets mature. In the absence of evidence, stakeholder confidence follows the last technology failure the organisation remembers — not the promise of the current programme. A consistent cadence of small, measurable, credible wins is the single most effective stakeholder management tool available to an AI programme leader.",
      why: "AI programmes that cannot point to near-term evidence of value lose budget, talent, and leadership support in exactly the window when long-term investments most need those resources. Quick wins are not a concession to impatience — they are the fuel that sustains the long-term journey.",
      paragraphs: [
        [
          s("The evidence gap is the most dangerous period of any AI programme. "),
          x(
            "The evidence gap is the period between initial investment approval — when stakeholder confidence is at its peak based on strategic rationale — and the delivery of first measurable outcomes. Every month in the evidence gap is a month where scepticism can accumulate and competing investment priorities can erode the programme's resources.",
            "Quick wins close the evidence gap. A credible business outcome delivered in month 6 resets the confidence clock — stakeholders who were becoming sceptical receive evidence that the investment is working, and the programme earns an extension of goodwill that longer-horizon investments require.",
          ),
          s(" Close the evidence gap with a specific, measurable, credible win in the first six months."),
        ],
        [
          s("Quick wins build the organisational capability that long-term bets need. "),
          x(
            "An organisation that has successfully deployed AI once has learned: how to define a use case with specific success criteria, how to run a pilot that tests hypotheses rather than demonstrates capabilities, how to manage vendor relationships, how to design the change management that drives adoption, and how to govern AI outputs with audit and override processes.",
            "Each of these capabilities is required by every subsequent AI deployment, increasingly so as the ambition of the deployment grows. Long-term, high-complexity AI bets fail more often in organisations that have not built these capabilities through smaller, lower-risk deployments.",
          ),
          s(" Every quick win is a capability investment in the organisation's AI readiness."),
        ],
        [
          s("Quick wins create institutional knowledge of what AI actually costs. "),
          x(
            "Business cases for long-term AI investments are more credible when the organisation has evidence from comparable smaller deployments. 'Based on our invoice matching deployment, which cost £180K to integrate and achieved 94% accuracy, we estimate the contract review programme at £420K integration with 91-95% accuracy' is a fundamentally more credible business case than one built on vendor estimates and industry benchmarks.",
            "The institutional knowledge generated by quick wins — real integration costs, real adoption timelines, real data quality problems, real vendor performance against SLA — reduces the business case uncertainty for long-term investments and earns them more credible approval.",
          ),
          s(" Quick win actuals are the benchmark data for long-term investment business cases."),
        ],
      ],
      examples: [
        {
          title: "JPMorgan — COIN as the evidence that funded AI transformation",
          body: "JPMorgan's COIN contract intelligence system — a quick win relative to the bank's ambitions — produced 360,000 hours of legal work in seconds. That specific, credible outcome was cited in every subsequent AI investment approval at the firm. The evidence from COIN did not just justify COIN's investment — it justified three years of AI infrastructure and capability investment that followed. The quick win was the evidence base for the transformation budget.",
        },
        {
          title: "A retailer — month 6 evidence resets the confidence clock",
          body: "A fashion retailer's AI programme was facing scepticism at month 5 from the CFO, who had not seen any measurable AI contribution to business performance. A product description AI initiative — deliberately scoped for 10-week delivery — produced a measurable 12% improvement in organic search conversion for AI-generated product descriptions at month 6. The CDO presented this at the executive committee. The CFO's response: 'If the larger initiatives produce proportionate results, this investment is clearly justified.' The quick win reset the confidence clock for the 18-month demand forecasting programme that was just entering pilot.",
        },
        {
          title: "A bank — quick win reveals real integration costs",
          body: "A bank's first AI deployment — document pre-processing for mortgage applications — took 16 weeks and cost £240K in integration engineering, against a vendor estimate of £80K. The actuals became the benchmark: all subsequent mortgage AI business cases used £240K as the integration estimate for comparable scope, not the vendor estimate. Two subsequent business cases that used the benchmark were approved without integration cost challenge; both came in within 15% of the benchmark. The quick win actuals produced credibility that vendor estimates never could.",
        },
      ],
    }, {
      kind: "diagram",
      id: "bl-pb2-ch07-7-1-why-quick-wins-matter",
      type: "flow",
      title: "Why Quick Wins Matter",
      caption:
        "Quick wins matter because they are the only evidence that an AI programme is producing value before long-term bets mature. In the absence of evidence,…",
    }),
    sectionWithDiagram({
      number: "7.2",
      title: "What Makes a Good Quick Win",
      subtitle: "The criteria that distinguish genuine quick wins from false starts",
      take: "Not every small, fast AI deployment is a good quick win. A good quick win is measurably valuable, credibly attributable to AI (not a concurrent process change), completed within 90 days of production deployment, and demonstrates a capability or approach that is replicable at greater scale. False starts — deployments that are fast but produce no credible evidence — are worse than no quick win because they consume credibility as well as budget.",
      why: "The quality of a quick win is more important than its speed. A poorly evidenced quick win that cannot be defended under scrutiny damages the programme's credibility more than the absence of a quick win. Define what makes a win credible before you commission it.",
      paragraphs: [
        [
          s("Measurability before speed — the win must be quantifiable. "),
          x(
            "A quick win that produces a directionally positive effect that cannot be precisely measured is not a credible win — it is an anecdote. The measurement standard: a specific metric, measured in the system that owns the metric, before and after the AI deployment, with any concurrent changes controlled for.",
            "The most common credibility failure: a process change and an AI deployment are implemented simultaneously, and the improvement is attributed to AI without isolating the AI contribution. A CFO who asks 'how do we know the improvement came from AI and not from the process change?' is asking a legitimate question. The measurement design must answer it before deployment.",
          ),
          s(" Design the measurement methodology before the deployment — not after the results come in."),
        ],
        [
          s("Credible attribution is the test that sceptics apply. "),
          x(
            "Stakeholders who are sceptical of AI investment will scrutinise quick win evidence for confounding explanations. Was the improvement seasonal? Did a market change coincide? Was it a Hawthorne effect from team attention? The win that survives these questions — because it was measured in a controlled way with a holdout group or a pre/post comparison on a stable metric — is the win that changes minds.",
            "The practical approach: where possible, deploy AI to a subset of the process (one geography, one product category, one customer segment) and compare AI-assisted performance to non-AI-assisted performance in a comparable subset. This A/B-style comparison is the most credible attribution design available in a business environment.",
          ),
          s(" A/B style deployment — AI-assisted vs non-AI — is the gold standard for quick win attribution."),
        ],
        [
          s("Replicability signals that the quick win is an investment, not an experiment. "),
          x(
            "A quick win that cannot be replicated or scaled is a successful experiment — interesting but not a business investment. The best quick wins demonstrate an approach, a data pipeline, or a vendor capability that can be applied to larger problems in the same domain.",
            "Before commissioning a quick win, ask: if this works, what larger opportunity does it unlock, and how? If the answer is 'nothing — this is standalone', reconsider whether it belongs in the portfolio as a quick win or as an isolated use case. Standalone quick wins are better than no evidence; replicable quick wins are better than standalone ones.",
          ),
          s(" Quick wins that unlock the next opportunity are investments; standalone ones are evidence only."),
        ],
      ],
      examples: [
        {
          title: "An insurer — measurement design that survived scrutiny",
          body: "An insurer's AI claims triage quick win was deployed to 50% of claims handlers (AI-assisted) with 50% as a control group (standard process) for 8 weeks. Results: AI-assisted group achieved 22% faster triage completion with 8% fewer re-opens. The CFO asked whether the improvement was because better performers were assigned to the AI group. The CDO produced the random assignment protocol. The question was answered; the win was credible. The measurement design had anticipated the scrutiny.",
        },
        {
          title: "A retailer — standalone quick win reconsidered",
          body: "A retailer proposed an AI quick win for seasonal trend identification in social media data. Delivery: 8 weeks. Expected value: £120K in trend-relevant purchasing decisions annually. Replicability: none — the vendor was a specialist social listening tool with no connection to the retailer's product or supply chain data. The governance committee reclassified it: a standalone use case, not a portfolio quick win. It was retained in the pipeline but not positioned as evidence for the broader AI programme investment decision. The distinction changed how its success was communicated to the board.",
        },
        {
          title: "A bank — quick win unlocks the next opportunity",
          body: "A bank's document pre-processing quick win used a data extraction pipeline that could be reused for three subsequent AI initiatives: mortgage application processing, commercial loan document review, and regulatory compliance filing analysis. The pipeline development — £180K of engineering — was justified in the quick win business case and reused at minimal marginal cost across the three subsequent initiatives. The quick win was an investment; the subsequent initiatives consumed the infrastructure it created.",
        },
      ],
    }, {
      kind: "diagram",
      id: "bl-pb2-ch07-7-2-what-makes-a-good-quick-win",
      type: "flow",
      title: "What Makes a Good Quick Win",
      caption:
        "Not every small, fast AI deployment is a good quick win. A good quick win is measurably valuable, credibly attributable to AI (not a concurrent process…",
    }),
    buildSection({
      number: "7.3",
      title: "The Danger of Only Quick Wins",
      subtitle: "When near-term optimisation crowds out long-term capability",
      take: "A portfolio of only quick wins is a portfolio of incrementalism. It improves operational efficiency, builds credibility, and develops capability — but it does not create the structural competitive advantages that long-term AI investment can produce. Leaders who respond to every portfolio pressure by adding quick wins and deferring long-term bets produce capable organisations that are progressively less competitive against peers who made the long-term investments.",
      why: "The danger is subtle: quick-win-only portfolios produce good performance metrics in the near term, which makes the absence of long-term bets invisible until a competitor's long-term bet matures and produces a structural advantage that quick wins cannot match.",
      paragraphs: [
        [
          s("Quick wins improve existing processes; long-term bets change competitive position. "),
          x(
            "Invoice processing automation that reduces cost per invoice from £8 to £2.50 is a genuine quick win — it delivers real ROI. But it does not change the bank's competitive position in business banking; it reduces operational cost. A long-term bet on AI credit risk assessment that enables real-time SME lending decisions changes what products the bank can offer — it changes competitive position.",
            "Both are valuable. The distinction is strategic: operational efficiency improvement is captured by the P&L in the near term; competitive position change is captured by market share over the medium term. A portfolio with only the former accumulates operational efficiency while losing market position.",
          ),
          s(" Operational efficiency AI and competitive position AI are both necessary — never conflate them."),
        ],
        [
          s("The compounding advantage of long-term AI investment only appears with patience. "),
          x(
            "Recommendation algorithms, fraud detection systems, and personalisation engines improve continuously as they process more data. The organisations that started these programmes five years ago have training data advantages that cannot be closed in twelve months regardless of investment level. The advantage is compounding over time — which means the penalty for starting late also compounds.",
            "Business leaders who defer long-term AI bets consistently discover, in year three or four, that they are trying to close a data advantage gap that has been widening for three or four years. The cost of the catch-up is higher than the cost of the original investment would have been.",
          ),
          s(" The cost of deferring long-term AI bets compounds over time — start before you need to."),
        ],
        [
          s("Quick-win culture can crowd out the appetite for uncertainty that long-term bets require. "),
          x(
            "Organisations that become expert at quick wins develop governance muscles optimised for certainty: clear metrics, short timelines, proven technology, high probability of success. Long-term bets require a different governance muscle: comfort with uncertainty, patience for leading-indicator evidence, and willingness to sustain investment through periods of ambiguous progress.",
            "Business leaders must consciously develop both governance muscles. The quick-win governance culture is not wrong — it is necessary. But it must be complemented by a genuinely different governance approach for long-term programmes, or those programmes will be managed to death by the standards of the quick-win culture.",
          ),
          s(" Long-term bets require a different governance culture — not an absence of governance."),
        ],
      ],
      examples: [
        {
          title: "A telecoms operator — operational efficiency without competitive position",
          body: "A European telecoms operator ran an AI programme that delivered £28M in operational efficiency savings over three years through call centre AI, network fault prediction, and billing query automation. In the same period, a competitor launched AI-personalised product bundles that reduced churn by 3.2 percentage points. The operational efficiency programme was genuinely excellent; the competitor's programme changed competitive position. The telecoms operator's CDO noted in the post-year-three review: 'We became the most efficient company in a market we were losing.'",
        },
        {
          title: "A bank — starting late on the data asset",
          body: "A regional bank deferred AI-powered credit scoring investment for three years, preferring quick wins in process automation. When it began the credit scoring programme, it discovered its primary data asset — transaction history — was less granular than competitors who had been collecting AI-relevant features (merchant category codes, time-of-day patterns, spending velocity signals) for five years. Closing the data feature gap added 18 months to the programme. The deferral cost was the accumulating data advantage the bank had conceded.",
        },
        {
          title: "A retailer — building long-term governance muscle",
          body: "A retailer's AI governance committee explicitly separated its governance processes by horizon. Horizon 1 quick wins had a 6-week approval cycle, standard gate criteria, and quarterly ROI reporting. Horizon 3 long-term bets had a separate governance track: an innovation committee with a Chief Strategy Officer chair, annual performance reviews with milestone metrics rather than outcome metrics, and a protected budget envelope. The separation prevented quick-win governance standards from being applied to long-term bets — preserving both.",
        },
      ],
    }),
    buildSection({
      number: "7.4",
      title: "Long-Term AI Requirements",
      subtitle: "What long-term AI bets need to succeed that quick wins do not",
      take: "Long-term AI investments require four things that quick wins typically do not need in the same measure: protected multi-year budget, executive sponsor continuity, data asset development as a distinct investment stream, and a governance cadence calibrated to the longer evidence cycle. Providing these without exception is the business leader's specific obligation to long-term AI programmes.",
      why: "Long-term AI programmes fail not because they are poorly designed but because the conditions they need to succeed — protected resources, sustained leadership attention, patient evidence expectations — are not maintained through the full investment horizon.",
      paragraphs: [
        [
          s("Multi-year budget protection cannot be conditional on annual re-approval. "),
          x(
            "A long-term AI programme that must re-justify its investment in every budget cycle will be defunded before it matures. The annual budget process is optimised for near-term returns; long-term investments systematically underperform against near-term investments at every annual review before their horizon arrives.",
            "The mechanism: multi-year budget envelope with annual milestone-based release conditions, as described in chapter 6. The milestone conditions must be calibrated to the long-term programme's evidence cycle — leading indicators, not lagging business outcomes — to avoid an evidence standard that only short-term programmes can meet.",
          ),
          s(" Multi-year envelope with milestone-based release: the only sustainable funding model for long-term AI."),
        ],
        [
          s("Executive sponsor continuity is the most fragile requirement. "),
          x(
            "Long-term AI programmes that survive an executive sponsor change are rare. When the sponsor leaves, the programme loses the political capital that protected it from resource competition, the institutional knowledge of why it was prioritised, and the board-level advocate who could defend continued investment against competing demands.",
            "Mitigation: before approving any long-term AI programme, identify the successor sponsor for the most likely transitions. Document the programme's strategic rationale in a form that the successor sponsor can absorb quickly. Build board-level familiarity with the programme that is independent of the primary sponsor relationship.",
          ),
          s(" Succession planning for long-term AI programme sponsors is a governance requirement, not an afterthought."),
        ],
        [
          s("Data asset development must be a distinct investment, not a programme dependency. "),
          x(
            "Long-term AI programmes that depend on data that does not yet exist in sufficient quality or volume must include explicit data asset development investment — separately budgeted, separately governed, and timed to be ready before the AI capability that needs it.",
            "Data asset development that is bundled into a long-term AI programme budget is frequently deprioritised during execution in favour of the more visible AI capability work. Separating the budget and governance ensures data readiness cannot be compromised without a visible decision.",
          ),
          s(" Separate data asset development budget and governance from the AI programme budget."),
        ],
      ],
      examples: [
        {
          title: "A financial services group — sponsor continuity plan",
          body: "A financial services group's AI personalisation programme — a 36-month horizon initiative — was approved with a CDO as primary sponsor. At approval, the programme governance committee documented three potential scenarios for sponsor transition: CDO internal transfer, CDO departure, and CDO remit change. Each scenario had a named successor sponsor and a hand-off protocol. When the CDO moved to a Group role at month 18, the documented succession plan produced a hand-off to the Chief Digital Products Officer in three weeks — the programme continued without a governance gap.",
        },
        {
          title: "A bank — data asset investment separated from AI programme",
          body: "A bank's AI credit risk programme identified a required data asset: a 5-year history of small business cash flow patterns linked to credit outcomes. This asset did not exist in structured form. Rather than bundling the data collection and structuring into the AI programme budget, the CDO created a separate data investment programme: £840K over 18 months for data collection design, collection system build, and quality assurance. The AI credit risk programme was approved for a start date 18 months out — after the data asset was ready. Both programmes were separately approved, separately governed, and separately reported. The AI programme launched on schedule on a ready data foundation.",
        },
        {
          title: "A manufacturer — milestone evidence calibrated to long horizon",
          body: "A manufacturer's AI materials science programme had a 30-month horizon. The governance committee designed milestone evidence requirements that were achievable at quarterly review points: month 3 — training data scope confirmed; month 6 — baseline model performance on known compounds; month 9 — first novel compound prediction within 8% of experimental value; month 12 — accuracy threshold met on the defined compound class. Each milestone was evidenced with data from the research programme. The governance committee received evidence-grade updates throughout, not just at the final outcome. Investment was sustained through three years.",
        },
      ],
    }),
    buildSection({
      number: "7.5",
      title: "Sequencing Quick Wins and Long-Term Bets",
      subtitle: "The portfolio design principle that makes both work",
      take: "The most effective AI programmes sequence quick wins and long-term bets so that each type of investment actively enables the other. Quick wins generate the evidence and capability that long-term bets depend on. Long-term bets leverage the data infrastructure and organisational capability that quick wins have built. The sequencing is deliberate — not accidental.",
      why: "Portfolios where quick wins and long-term bets are independent of each other miss the compounding value that comes from deliberate sequencing. The business leader who designs the portfolio sees the connection between a quick win in customer data processing and a long-term bet on customer intelligence — the quick win builds the data pipeline that the long-term bet needs.",
      paragraphs: [
        [
          s("Design quick wins that create the infrastructure for long-term bets. "),
          x(
            "A quick win in invoice processing builds a document extraction pipeline. A long-term bet on AI contract management needs a document extraction pipeline. Sequencing the quick win before the long-term bet means the long-term bet starts with infrastructure — not from zero.",
            "This requires knowing, before commissioning the quick win, which long-term bet it will enable. That knowledge changes the quick win's technical design — it builds for the future dependency, not just for the immediate use case. The additional cost is small; the compounding value is significant.",
          ),
          s(" Design quick win technical architecture for the long-term bet it will enable."),
        ],
        [
          s("Use quick win evidence to calibrate long-term bet business cases. "),
          x(
            "The quick win in a domain — customer service AI, supply chain AI, financial document AI — produces real performance data: actual accuracy, actual integration cost, actual adoption timeline, actual governance requirements. This data is the best available input for a long-term bet business case in the same domain.",
            "The sequencing principle: run the quick win before finalising the long-term bet business case in the same domain. The quick win data will either confirm the long-term bet assumptions (proceed with confidence) or challenge them (redesign before committing long-term resources).",
          ),
          s(" Finalise the long-term bet business case after the quick win in the same domain has run."),
        ],
        [
          s("Communicate the sequencing logic explicitly to stakeholders. "),
          x(
            "Stakeholders who see a portfolio of small initiatives and a separate portfolio of large, long-horizon investments may not understand that they are connected. The sequencing logic — 'these quick wins are building the foundations and the evidence for these long-term bets' — must be made explicit.",
            "A sequencing narrative for stakeholders: 'Phase 1 quick wins (months 1-18) build the data infrastructure, prove the AI capability in our environment, and develop the organisational change management competence that Phase 2 long-term programmes require. Phase 2 long-term programmes (months 12-42) use the infrastructure Phase 1 built and are calibrated on Phase 1 evidence.' This narrative makes the connection visible and the portfolio rationale comprehensible.",
          ),
          s(" The sequencing narrative is the business leader's tool for making a complex portfolio comprehensible."),
        ],
      ],
      examples: [
        {
          title: "A bank — pipeline investment that unlocked three programmes",
          body: "A bank's quick win in mortgage document pre-processing deliberately built a document extraction API designed for reuse. The API used a standard interface that the technology team could call from any system. Eighteen months later, three long-term programmes — commercial loan documents, regulatory filing analysis, and customer correspondence management — used the same API. The API development cost £120K more than a single-use solution would have. It saved an estimated £840K in de-duplicated development across the three long-term programmes.",
        },
        {
          title: "An insurer — quick win recalibrates a long-term bet",
          body: "An insurer's quick win in claims document classification achieved 89% accuracy — below the 95% expected in the long-term automation business case. The discovery: handwritten sections of claim forms were significantly degrading accuracy. The quick win data prompted a redesign of the long-term automation programme before it was approved: the programme scope was adjusted to exclude handwritten claim sections (redirected to a digitisation programme), and the business case was revised with the 89% realistic accuracy figure. The long-term programme was approved on revised assumptions — assumptions that proved accurate.",
        },
        {
          title: "A retailer — sequencing narrative that earned sustained investment",
          body: "A retailer's CDO presented the programme sequencing narrative at the annual board review: 'Phase 1 quick wins have built the customer data pipeline, proved AI personalisation in a limited product category, and developed 12 members of our team into competent AI programme managers. Phase 2 programmes — full personalisation and AI range planning — use the pipeline Phase 1 built and are led by the programme managers Phase 1 developed. Without Phase 1, Phase 2 would have started cold on both fronts.' The board approved Phase 2 investment with no further challenge. The sequencing narrative made Phase 2 feel like a logical continuation, not a new bet.",
        },
      ],
    }),
    buildSection({
      number: "7.6",
      title: "Communicating Horizons to Stakeholders",
      subtitle: "Managing the expectations of audiences with different time preferences",
      take: "Different stakeholders have different time preferences for AI investment returns. Boards have fiduciary horizons. Operational leaders have quarterly performance horizons. Customers have experiential horizons that are measured in seconds. Employees have career horizons. Business leaders who understand these different preferences can tailor their AI portfolio communication to each audience without changing the substance of the portfolio.",
      why: "Stakeholder communication that ignores time preference misalignment consistently produces either impatient boards demanding quick wins that undermine long-term bets, or operational teams pursuing long-term programmes that undermine short-term performance. Tailored communication is not spin — it is the business leader's responsibility.",
      paragraphs: [
        [
          s("Map stakeholder time preferences before designing the communication. "),
          x(
            "Board members on nomination and remuneration committees typically have three to five year time horizons — they think in strategy cycles. Chief Financial Officers typically think in fiscal years with quarterly check-ins. Operational managers think in monthly performance targets. Front-line employees think in daily workflow impact.",
            "The same portfolio produces different messages for each audience. Board: 'This three-year programme positions us against the competitive threat we discussed at the strategy day.' CFO: 'Year 1 returns are £1.1M; Year 2 commitments are milestone-gated at £2.1M.' Operational manager: 'Your team will see the first AI-assisted workflows in April; we have a training programme starting in March.'",
          ),
          s(" Same portfolio, different message emphasis by audience time horizon."),
        ],
        [
          s("Never let long-term narrative crowd out short-term evidence. "),
          x(
            "Leaders who are enthusiastic about long-term AI ambition sometimes communicate so much about the three-to-five year vision that stakeholders with short time preferences stop listening. The long-term narrative earns less attention if there is no near-term evidence to validate the credibility of the long-term claim.",
            "The communication sequence: lead with near-term evidence ('in the last quarter, AI processing saved £380K in invoice handling costs'), then the medium-term trajectory ('on current trajectory, annual savings will reach £1.8M by year two'), then the long-term thesis ('this data infrastructure positions us for the AI-enabled supply chain programme that represents our primary competitive investment in year three').",
          ),
          s(" Near-term evidence first earns the credibility to make long-term claims heard."),
        ],
        [
          s("Protect the programme from short-term stakeholder pressure without losing their support. "),
          x(
            "Boards and CFOs under quarterly performance pressure will seek to redirect long-term AI investment toward near-term returns. The protection is not refusal — it is the multi-year envelope with milestone conditions, which provides finance with the accountability framework they need while protecting programme continuity.",
            "The specific language: 'The long-term investment is milestone-gated — it releases on evidence of progress, not on calendar time. If the milestones are not met, the investment is not released. This protects the organisation from committing to underperforming long-term programmes while giving successful programmes the certainty they need.' This language converts a governance debate into a governance alignment.",
          ),
          s(" Milestone-gated multi-year envelopes protect long-term programmes from short-term pressure while giving finance appropriate accountability."),
        ],
      ],
      examples: [
        {
          title: "A financial services group — audience-tailored communication",
          body: "A financial services group's AI portfolio was communicated through three different annual review formats: a Board strategy paper (three-year horizon, competitive positioning, risk and opportunity framing), a CFO investment summary (fiscal year ROI, milestone release conditions, programme health metrics), and an operational leader briefing (team impact, workflow changes, Q2-Q3 deployment schedule). The same portfolio, same facts, three tailored communication formats. The Head of Investor Relations noted that analyst questions about AI strategy — which had previously been answered inconsistently across executives — were consistent for the first time, because all executives had been briefed from the same facts differently emphasised.",
        },
        {
          title: "A retailer — near-term evidence validates long-term claim",
          body: "A retailer's CDO had attempted for two quarters to earn board support for a three-year AI personalisation programme by presenting the strategic ambition. The board was interested but not convinced. In Q3, the CDO presented the AI product description quick win evidence first: 'AI-generated descriptions produced 12% better search conversion in a controlled A/B test, delivering £840K in incremental annual revenue from this one use case.' Then: 'The same personalisation capability at full scale — product, pricing, communication — is the three-year programme. This is a proof point of the scale ambition.' The board approved the three-year programme in the same session.",
        },
        {
          title: "A bank — milestone language that converted the CFO",
          body: "A bank's CFO had blocked a long-term AI credit risk programme on the grounds that year-two and year-three investment commitments were too uncertain. The CDO proposed milestone language: year-two funding released only on three conditions: model accuracy above 90% on the holdout set, pilot producing measurable underwriting efficiency improvement, and regulatory pre-approval letter received. The CFO agreed: 'I can approve year-two funding conditionally on those conditions. If they're not met, the investment doesn't release.' The milestone language gave the CFO the accountability framework and the CDO the programme certainty — converting a block into an approval.",
        },
      ],
    }),
    buildSection({
      number: "7.7",
      title: "When to Stop a Long-Term Bet",
      subtitle: "The hardest AI portfolio decision — and how to make it without regret",
      take: "Stopping a long-term AI bet is the hardest decision in portfolio management. The sunk cost is real, the future potential feels compelling, and the sponsor is invested. The decision framework must be based on evidence about whether the bet's assumptions remain valid — not on the size of the investment made. A stopped bet that releases resources for better-prioritised investments is a better outcome than a continued bet that consumes resources without creating value.",
      why: "Long-term bets that should be stopped are routinely continued because the decision framework for stopping them does not exist or is not applied. Leaders who create an explicit stopping framework before programmes begin remove the emotional and political difficulty from the decision when it arises.",
      paragraphs: [
        [
          s("Define stopping conditions before the programme begins. "),
          x(
            "Every long-term AI bet should have pre-defined stopping conditions alongside its milestone conditions. Stopping conditions are the signals that indicate the underlying strategic assumption has been invalidated: 'If the model cannot achieve 85% accuracy on our production data within the pilot phase, we will stop.' 'If the regulatory framework changes to classify this use case as prohibited, we will stop.'",
            "Stopping conditions defined in advance remove the decision from the moment of difficulty — when sunk cost, sponsor relationships, and organisational momentum create pressure to continue. A programme that meets its pre-defined stopping condition is stopped; a programme that does not, is not. The framework makes the decision, not the committee.",
          ),
          s(" Define stopping conditions at programme approval — before investment creates momentum."),
        ],
        [
          s("Distinguish between a bet that should be stopped and a bet that should be redesigned. "),
          x(
            "A long-term bet that has encountered a solvable problem — data quality that can be improved, a regulatory barrier that can be navigated, an adoption design that can be fixed — is a redesign candidate, not a stop candidate. A bet that has encountered an unsolvable fundamental problem — the technology cannot achieve the required performance level, the market has moved making the value hypothesis invalid — is a stop candidate.",
            "The test: can we identify a specific intervention — costed and timed — that would resolve the current issue and get the programme back to its milestone trajectory? If yes, the programme is a redesign candidate. If no credible intervention exists, the programme is a stop candidate.",
          ),
          s(" Redesign when a specific intervention exists; stop when no credible intervention can restore the milestone trajectory."),
        ],
        [
          s("Stopping well generates as much value as stopping at the right time. "),
          x(
            "A well-executed stop generates: a candid post-mortem that identifies which assumption failed and why, documented findings that improve future business case quality, release of resources to better-prioritised investments, and a clear communication to stakeholders that explains the stop in terms of changed conditions rather than programme failure.",
            "A poorly executed stop — abrupt, without post-mortem, communicated as failure — produces the opposite: the organisation learns nothing, the team is demoralised, and stakeholders become more risk-averse about approving future long-term bets. Stopping is an art. Practise it before you need to.",
          ),
          s(" Stop with a post-mortem, a communication, and a resource release plan — not just a decision."),
        ],
      ],
      examples: [
        {
          title: "A bank — stopping condition applied without drama",
          body: "A bank's AI trading analytics programme had a pre-defined stopping condition: if the model could not achieve 70% directional accuracy on out-of-sample data within the pilot phase, the programme would be stopped. At month 7, the pilot produced 61% accuracy after three iterations. The stopping condition was triggered without debate — the programme governance framework made the decision. The post-mortem identified that market regime changes during the pilot period had produced training data that was unrepresentative of the deployment environment. The finding was incorporated into the business case for a successor programme three cycles later.",
        },
        {
          title: "A retailer — redesign vs. stop",
          body: "A fashion retailer's AI markdown optimisation programme was hitting milestone shortfalls at month 12 — model accuracy was 78% against a 90% target. A stopping condition review was conducted. The intervention assessment: a data quality remediation project, 10 weeks, £180K, would provide the product-level feature set the model needed. The assessment was credible; the intervention was specific and costed. The programme was redesigned — the redesign was approved. At month 22, accuracy had reached 89%. The redesign was the correct decision over the stop.",
        },
        {
          title: "An insurer — stopping communication that preserved future investment appetite",
          body: "An insurer stopped a two-year AI claims prediction programme when the EU AI Act's risk classification changed the governance requirements beyond what the programme's design could accommodate without a fundamental rebuild. The stop communication to the executive committee: 'We are stopping the claims prediction programme because the regulatory environment has changed in a way that makes our current approach non-viable. The data asset and model architecture we have developed are applicable to a different use case with lower regulatory risk — we will bring a revised proposal in Q3. The resources released are redirected to the three-component claims programme that is already in production.' The stop was received as a sound management decision, not as a failure. Future investment appetite was maintained.",
        },
      ],
    }),
    buildSection({
      number: "7.8",
      title: "The Business Leader's Portfolio Balance",
      subtitle: "A framework for managing the horizon tension in practice",
      take: "The practical discipline is simple in principle and demanding in practice: maintain explicit targets for portfolio balance across three horizons, review balance at each quarterly governance meeting, protect each horizon from the other's gravitational pull, and communicate the rationale for the balance at every board and leadership touchpoint. This is the business leader's primary portfolio governance responsibility.",
      why: "Portfolio balance does not maintain itself — it requires active, ongoing management by the business leader. The gravity of near-term pressure on long-term bets and the pull of technological ambition on near-term delivery will move the portfolio away from balance without active leadership intervention.",
      paragraphs: [
        [
          s("Set explicit investment targets by horizon before reviewing the portfolio. "),
          x(
            "Before reviewing the portfolio, set targets: Horizon 1 (operating AI, 0-12 months to outcome) should represent X% of the AI investment budget; Horizon 2 (growing AI, 12-24 months) Y%; Horizon 3 (emerging AI, 24+ months) Z%. The specific percentages should be calibrated to the organisation's AI maturity, competitive environment, and risk appetite — not copied from a template.",
            "Organisations in early AI maturity should target higher Horizon 1 percentages — the evidence cadence matters most when stakeholder confidence is being built from scratch. Organisations with established programmes and board confidence can shift more toward Horizon 2 and 3 without risking credibility. The targets should evolve as the programme matures.",
          ),
          s(" Set horizon targets before reviewing the portfolio — pre-commitment prevents in-session bias."),
        ],
        [
          s("Review balance explicitly at every quarterly governance meeting. "),
          x(
            "Portfolio balance reviews have a single question: does the current distribution of investment across horizons match the targets? If yes, the balance check takes five minutes. If no — if the portfolio has drifted Horizon 1-heavy because three long-term programmes were stopped or Horizon 3-heavy because three quick wins completed — the imbalance is flagged for correction in the next cycle.",
            "The correction is typically one of three actions: accelerate a deferred programme from a deferred horizon, pause a programme from the over-represented horizon to release capacity, or commission a new programme assessment in the under-represented horizon for the next cycle.",
          ),
          s(" Balance review: five questions, five minutes, three possible actions."),
        ],
        [
          s("The balance narrative is the business leader's most consistent communication. "),
          x(
            "At every board meeting, every leadership update, every investor question about AI — the business leader should be able to describe the portfolio balance in thirty seconds: 'We have four Horizon 1 initiatives producing outcomes now, three Horizon 2 initiatives building capability for deployment in 12-18 months, and one Horizon 3 programme representing our long-term competitive bet. The balance is deliberate — near-term wins fund the credibility for long-term investment, and the long-term bet is the position we're building toward.'",
            "Leaders who can give this narrative consistently — without reference to a slide — are demonstrating portfolio management mastery to every stakeholder audience. It signals a programme that is actively managed, not passively accumulated.",
          ),
          s(" Thirty-second portfolio balance narrative: the signal of portfolio management mastery."),
        ],
      ],
      examples: [
        {
          title: "A financial services group — maturity-adjusted horizon targets",
          body: "A financial services group adjusted its AI portfolio horizon targets as the programme matured: Year 1 — 70% Horizon 1, 20% Horizon 2, 10% Horizon 3. Year 2 — 50% Horizon 1, 35% Horizon 2, 15% Horizon 3. Year 3 — 40% Horizon 1, 35% Horizon 2, 25% Horizon 3. The shift reflected increasing stakeholder confidence (less need for near-term evidence) and increasing organisational capability (readiness for more complex long-term programmes). The targets were reviewed annually by the board as part of the AI strategy review.",
        },
        {
          title: "A retailer — balance correction in quarterly review",
          body: "A retailer's Q2 quarterly review balance check revealed: two Horizon 1 programmes had completed, one Horizon 2 programme had been promoted to Horizon 1 on ahead-of-schedule performance — and no new Horizon 2 or 3 programmes had entered the assessment pipeline. The portfolio was now 90% Horizon 1 against a 50% target. Correction: three previously deferred Horizon 2 candidates were brought forward for assessment, and the Horizon 3 programme that had been awaiting sponsor confirmation was approved to enter the portfolio. The balance correction took one quarterly review; without the explicit balance check, the drift would have continued undetected.",
        },
        {
          title: "A bank — thirty-second narrative at investor day",
          body: "A bank's Chief Digital Officer was asked at an investor day Q&A: 'Can you characterise your AI investment portfolio?' Response (delivered without slides): 'We have five programmes delivering measurable returns now — £28M in annualised value. Three programmes in the 12-to-18-month horizon, building on the data infrastructure the first five created. And one long-term programme in AI credit risk assessment that represents our primary competitive investment — we expect it to change our SME lending economics materially by year four.' The investor's follow-up question was about the SME lending market, not about AI programme management. The narrative had worked.",
        },
      ],
    }),
  ],
  quiz: [
    {
      q: "Your AI programme is at month 8 with no delivered business outcome. The long-term programmes are on milestone track. What is the most important corrective action?",
      options: [
        "Continue — long-term programmes take time.",
        "Add a quick win initiative scoped for 6-8 week delivery to close the evidence gap before stakeholder confidence erodes further.",
        "Increase communication frequency to buy more time.",
        "Redefine a milestone as a business outcome to satisfy the evidence requirement.",
      ],
      correct: 1,
      correctFeedback:
        "Right. Month 8 without a delivered outcome is in the evidence gap. A quick win scoped for near-term delivery is the corrective action — not more communication or redefined milestones. The goal is genuine evidence, not the appearance of it. Re-read section 7.1.",
      wrongFeedback:
        "Communication without evidence buys goodwill, not confidence. And redefining milestones as outcomes is the governance failure the chapter warns against. A genuine quick win is the required action. Re-read section 7.1.",
    },
    {
      q: "A proposed quick win will deliver a measurable outcome in 8 weeks. However, it cannot be replicated or scaled, and shares no infrastructure with any other programme. How should it be classified?",
      options: [
        "A strong quick win — speed and measurability are the primary criteria.",
        "A standalone use case — valuable as evidence, but should not be counted as a quick win that unlocks broader portfolio value.",
        "A long-term bet because it lacks scale.",
        "Not worth doing — replicability is mandatory.",
      ],
      correct: 1,
      correctFeedback:
        "Right. Replicability determines whether a quick win is an investment or merely evidence. Standalone use cases are still worth doing, but they should be classified and communicated correctly — they are not the same as replicable quick wins that compound portfolio value. Re-read section 7.2.",
      wrongFeedback:
        "Speed and measurability are necessary but not sufficient for a high-quality quick win. Replicability determines whether the win compounds into portfolio value or remains isolated. Re-read section 7.2.",
    },
    {
      kind: "categorize",
      q: "Sort each portfolio characteristic into the horizon category it describes.",
      categories: ["Horizon 1 — operating AI", "Horizon 2 — growing AI", "Horizon 3 — emerging AI"],
      items: [
        { text: "An AI programme producing measurable ROI from invoice processing automation, fully deployed.", category: 0 },
        { text: "An AI programme in pilot phase for claims triage, expected to reach full deployment in 14 months.", category: 1 },
        { text: "An AI-enabled business model experiment in outcome-based pricing, 36-month horizon.", category: 2 },
        { text: "An AI demand forecasting system live in production, saving £1.2M annually.", category: 0 },
        { text: "An AI personalisation programme with data infrastructure being built, expected first outcome in 18 months.", category: 1 },
      ],
      correctFeedback:
        "Right. Horizon classification is based on time to first business outcome, not on complexity or investment size. Operating AI is producing outcomes now; growing AI is building toward outcomes in 12-24 months; emerging AI is exploring 24+ month competitive positions. Re-read sections 7.3 and 7.8.",
      wrongFeedback:
        "Horizon classification is based on time to first business outcome, not on technical sophistication. A technically simple programme that produces outcomes now is Horizon 1; a technically complex programme not yet in production is Horizon 2 or 3. Re-read section 7.8.",
    },
    {
      q: "A long-term AI bet has been running for 18 months. It has missed its last two milestone targets. Your team proposes continuing with a revised timeline. What is the governance-correct response?",
      options: [
        "Accept the revised timeline — complex programmes always take longer than planned.",
        "Apply the stopping condition test: is there a specific, costed intervention that would restore the milestone trajectory? If yes, redesign. If no credible intervention exists, stop.",
        "Stop immediately — missed milestones always mean failure.",
        "Reduce the programme's budget to reduce exposure and continue.",
      ],
      correct: 1,
      correctFeedback:
        "Right. The stopping condition test distinguishes between a redesign candidate and a stop candidate. The test is specific: does a credible intervention exist? A revised timeline without an identified intervention is a deferral, not a redesign. Re-read section 7.7.",
      wrongFeedback:
        "Missed milestones alone do not determine stop vs. redesign — the existence of a credible, specific intervention does. Re-read section 7.7.",
    },
    {
      q: "A board member asks why the AI portfolio includes small invoice processing initiatives alongside a three-year AI credit risk programme. What is the correct response?",
      options: [
        "The small initiatives were approved first and are running while the large programme is developed.",
        "The invoice processing initiatives build the document processing infrastructure and organisational AI capability that the credit risk programme requires — and produce the near-term evidence that sustains board confidence through the credit risk programme's longer horizon.",
        "They are independent — we fund all justified AI investments.",
        "The invoice processing initiatives are in a separate budget and do not affect the credit risk programme.",
      ],
      correct: 1,
      correctFeedback:
        "Right. The sequencing narrative — quick wins build infrastructure and evidence for long-term bets — is the explanation that makes a mixed-horizon portfolio comprehensible and defensible. Re-read section 7.5.",
      wrongFeedback:
        "The board deserves the sequencing rationale, not just an explanation that the investments are independent. The connection between quick wins and long-term bets is the portfolio logic that earns sustained investment approval. Re-read section 7.5.",
    },
    {
      kind: "order",
      q: "Order the steps for stopping a long-term AI bet in the correct sequence.",
      prompt: "Drag to arrange from first step (top) to last (bottom).",
      items: [
        "Apply the stopping condition test: has a pre-defined stopping condition been triggered, or is there no credible intervention to restore milestone trajectory?",
        "Conduct a post-mortem to identify which assumption failed and why.",
        "Communicate the stop to stakeholders, framing it in terms of changed conditions rather than programme failure.",
        "Release resources to better-prioritised investments and document the reallocation.",
      ],
      correctFeedback:
        "Right. The stopping condition test makes the decision; the post-mortem generates the learning; the communication manages stakeholder expectations; the resource release produces the portfolio value from stopping. Each step depends on the previous one. Re-read section 7.7.",
      wrongFeedback:
        "The sequence matters: the decision must precede the communication, and the learning from the post-mortem must be captured before resources are released. Re-read section 7.7.",
    },
  ],
});
