/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlaybooksRouteImport } from './routes/playbooks'
import { Route as PlaybookRouteImport } from './routes/playbook'
import { Route as GlossaryRouteImport } from './routes/glossary'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlaybookIndexRouteImport } from './routes/playbook.index'
import { Route as PlaybookSlugRouteImport } from './routes/playbook.$slug'

const PlaybooksRoute = PlaybooksRouteImport.update({
  id: '/playbooks',
  path: '/playbooks',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybookRoute = PlaybookRouteImport.update({
  id: '/playbook',
  path: '/playbook',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryRoute = GlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybookIndexRoute = PlaybookIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlaybookRoute,
} as any)
const PlaybookSlugRoute = PlaybookSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PlaybookRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/glossary': typeof GlossaryRoute
  '/playbook': typeof PlaybookRouteWithChildren
  '/playbooks': typeof PlaybooksRoute
  '/playbook/$slug': typeof PlaybookSlugRoute
  '/playbook/': typeof PlaybookIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/glossary': typeof GlossaryRoute
  '/playbooks': typeof PlaybooksRoute
  '/playbook/$slug': typeof PlaybookSlugRoute
  '/playbook': typeof PlaybookIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/glossary': typeof GlossaryRoute
  '/playbook': typeof PlaybookRouteWithChildren
  '/playbooks': typeof PlaybooksRoute
  '/playbook/$slug': typeof PlaybookSlugRoute
  '/playbook/': typeof PlaybookIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/glossary'
    | '/playbook'
    | '/playbooks'
    | '/playbook/$slug'
    | '/playbook/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/glossary'
    | '/playbooks'
    | '/playbook/$slug'
    | '/playbook'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/glossary'
    | '/playbook'
    | '/playbooks'
    | '/playbook/$slug'
    | '/playbook/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  GlossaryRoute: typeof GlossaryRoute
  PlaybookRoute: typeof PlaybookRouteWithChildren
  PlaybooksRoute: typeof PlaybooksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/playbooks': {
      id: '/playbooks'
      path: '/playbooks'
      fullPath: '/playbooks'
      preLoaderRoute: typeof PlaybooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbook': {
      id: '/playbook'
      path: '/playbook'
      fullPath: '/playbook'
      preLoaderRoute: typeof PlaybookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbook/': {
      id: '/playbook/'
      path: '/'
      fullPath: '/playbook/'
      preLoaderRoute: typeof PlaybookIndexRouteImport
      parentRoute: typeof PlaybookRoute
    }
    '/playbook/$slug': {
      id: '/playbook/$slug'
      path: '/$slug'
      fullPath: '/playbook/$slug'
      preLoaderRoute: typeof PlaybookSlugRouteImport
      parentRoute: typeof PlaybookRoute
    }
  }
}

interface PlaybookRouteChildren {
  PlaybookSlugRoute: typeof PlaybookSlugRoute
  PlaybookIndexRoute: typeof PlaybookIndexRoute
}

const PlaybookRouteChildren: PlaybookRouteChildren = {
  PlaybookSlugRoute: PlaybookSlugRoute,
  PlaybookIndexRoute: PlaybookIndexRoute,
}

const PlaybookRouteWithChildren = PlaybookRoute._addFileChildren(
  PlaybookRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  GlossaryRoute: GlossaryRoute,
  PlaybookRoute: PlaybookRouteWithChildren,
  PlaybooksRoute: PlaybooksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
