/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PlaybooksRouteImport } from './routes/playbooks'
import { Route as PlaybookRouteImport } from './routes/playbook'
import { Route as GamesRouteImport } from './routes/games'
import { Route as CreatorRouteImport } from './routes/creator'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlaybooksIndexRouteImport } from './routes/playbooks.index'
import { Route as PlaybookSlugRouteImport } from './routes/playbook.$slug'
import { Route as GamesAgentOverseerRouteImport } from './routes/games_.agent-overseer'
import { Route as PlaybooksPlaybookIdChapterSlugRouteImport } from './routes/playbooks.$playbookId.$chapterSlug'

const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybooksRoute = PlaybooksRouteImport.update({
  id: '/playbooks',
  path: '/playbooks',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybookRoute = PlaybookRouteImport.update({
  id: '/playbook',
  path: '/playbook',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorRoute = CreatorRouteImport.update({
  id: '/creator',
  path: '/creator',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybooksIndexRoute = PlaybooksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlaybooksRoute,
} as any)
const PlaybookSlugRoute = PlaybookSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PlaybookRoute,
} as any)
const GamesAgentOverseerRoute = GamesAgentOverseerRouteImport.update({
  id: '/games_/agent-overseer',
  path: '/games/agent-overseer',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybooksPlaybookIdChapterSlugRoute =
  PlaybooksPlaybookIdChapterSlugRouteImport.update({
    id: '/$playbookId/$chapterSlug',
    path: '/$playbookId/$chapterSlug',
    getParentRoute: () => PlaybooksRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/creator': typeof CreatorRoute
  '/games': typeof GamesRoute
  '/playbook': typeof PlaybookRouteWithChildren
  '/playbooks': typeof PlaybooksRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/games/agent-overseer': typeof GamesAgentOverseerRoute
  '/playbook/$slug': typeof PlaybookSlugRoute
  '/playbooks/': typeof PlaybooksIndexRoute
  '/playbooks/$playbookId/$chapterSlug': typeof PlaybooksPlaybookIdChapterSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/creator': typeof CreatorRoute
  '/games': typeof GamesRoute
  '/playbook': typeof PlaybookRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/games/agent-overseer': typeof GamesAgentOverseerRoute
  '/playbook/$slug': typeof PlaybookSlugRoute
  '/playbooks': typeof PlaybooksIndexRoute
  '/playbooks/$playbookId/$chapterSlug': typeof PlaybooksPlaybookIdChapterSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/creator': typeof CreatorRoute
  '/games': typeof GamesRoute
  '/playbook': typeof PlaybookRouteWithChildren
  '/playbooks': typeof PlaybooksRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/games_/agent-overseer': typeof GamesAgentOverseerRoute
  '/playbook/$slug': typeof PlaybookSlugRoute
  '/playbooks/': typeof PlaybooksIndexRoute
  '/playbooks/$playbookId/$chapterSlug': typeof PlaybooksPlaybookIdChapterSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/creator'
    | '/games'
    | '/playbook'
    | '/playbooks'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/terms-of-service'
    | '/games/agent-overseer'
    | '/playbook/$slug'
    | '/playbooks/'
    | '/playbooks/$playbookId/$chapterSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/creator'
    | '/games'
    | '/playbook'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/terms-of-service'
    | '/games/agent-overseer'
    | '/playbook/$slug'
    | '/playbooks'
    | '/playbooks/$playbookId/$chapterSlug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/creator'
    | '/games'
    | '/playbook'
    | '/playbooks'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/terms-of-service'
    | '/games_/agent-overseer'
    | '/playbook/$slug'
    | '/playbooks/'
    | '/playbooks/$playbookId/$chapterSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  CreatorRoute: typeof CreatorRoute
  GamesRoute: typeof GamesRoute
  PlaybookRoute: typeof PlaybookRouteWithChildren
  PlaybooksRoute: typeof PlaybooksRouteWithChildren
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  GamesAgentOverseerRoute: typeof GamesAgentOverseerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbooks': {
      id: '/playbooks'
      path: '/playbooks'
      fullPath: '/playbooks'
      preLoaderRoute: typeof PlaybooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbook': {
      id: '/playbook'
      path: '/playbook'
      fullPath: '/playbook'
      preLoaderRoute: typeof PlaybookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator': {
      id: '/creator'
      path: '/creator'
      fullPath: '/creator'
      preLoaderRoute: typeof CreatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbooks/': {
      id: '/playbooks/'
      path: '/'
      fullPath: '/playbooks/'
      preLoaderRoute: typeof PlaybooksIndexRouteImport
      parentRoute: typeof PlaybooksRoute
    }
    '/playbook/$slug': {
      id: '/playbook/$slug'
      path: '/$slug'
      fullPath: '/playbook/$slug'
      preLoaderRoute: typeof PlaybookSlugRouteImport
      parentRoute: typeof PlaybookRoute
    }
    '/games_/agent-overseer': {
      id: '/games_/agent-overseer'
      path: '/games/agent-overseer'
      fullPath: '/games/agent-overseer'
      preLoaderRoute: typeof GamesAgentOverseerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbooks/$playbookId/$chapterSlug': {
      id: '/playbooks/$playbookId/$chapterSlug'
      path: '/$playbookId/$chapterSlug'
      fullPath: '/playbooks/$playbookId/$chapterSlug'
      preLoaderRoute: typeof PlaybooksPlaybookIdChapterSlugRouteImport
      parentRoute: typeof PlaybooksRoute
    }
  }
}

interface PlaybookRouteChildren {
  PlaybookSlugRoute: typeof PlaybookSlugRoute
}

const PlaybookRouteChildren: PlaybookRouteChildren = {
  PlaybookSlugRoute: PlaybookSlugRoute,
}

const PlaybookRouteWithChildren = PlaybookRoute._addFileChildren(
  PlaybookRouteChildren,
)

interface PlaybooksRouteChildren {
  PlaybooksIndexRoute: typeof PlaybooksIndexRoute
  PlaybooksPlaybookIdChapterSlugRoute: typeof PlaybooksPlaybookIdChapterSlugRoute
}

const PlaybooksRouteChildren: PlaybooksRouteChildren = {
  PlaybooksIndexRoute: PlaybooksIndexRoute,
  PlaybooksPlaybookIdChapterSlugRoute: PlaybooksPlaybookIdChapterSlugRoute,
}

const PlaybooksRouteWithChildren = PlaybooksRoute._addFileChildren(
  PlaybooksRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  CreatorRoute: CreatorRoute,
  GamesRoute: GamesRoute,
  PlaybookRoute: PlaybookRouteWithChildren,
  PlaybooksRoute: PlaybooksRouteWithChildren,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  GamesAgentOverseerRoute: GamesAgentOverseerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
